import { Hono } from "hono";
import type { DatabaseEnv } from "./db";
import { ensureSchema } from "./ensure-schema";
import { createLogger, type LoggerEnv } from "./logger";
import account from "./routes/account";
import admin from "./routes/admin";
import api from "./routes/api";
import host from "./routes/host";
import pages from "./routes/pages";

type Bindings = LoggerEnv &
  DatabaseEnv & {
    /** File storage. Design assets from `design/assets/` live under the `assets/` prefix. */
    BUCKET?: R2Bucket;
  };

const app = new Hono<{ Bindings: Bindings }>();

/**
 * The JSON API — circles, gatherings, the calendar, and the signed-in member.
 * Mounted here so the router owns its own paths (`/health` inside becomes
 * `/api/health` outside). It also serves the liveness probe.
 */
/**
 * Build the schema on first use if the platform has not. The deploy pipeline
 * creates no tables, so without this a fresh deployment 500s on every page that
 * reads data. Skipped for the liveness probe and static assets, which must keep
 * answering even when the database is unreachable. See src/ensure-schema.ts.
 */
app.use("*", async (c, next) => {
  const path = c.req.path;
  if (path !== "/api/health" && !path.startsWith("/assets/")) {
    await ensureSchema(c.env);
  }
  await next();
});

/**
 * One-time bootstrap for the deployed database. Inert unless ADMIN_TOKEN is set
 * in the Loop dashboard — see src/routes/admin.ts.
 */
app.route("/api/admin", admin);

app.route("/api", api);

/**
 * The HTML app. Mounted at the root, so each router owns its own paths:
 * `pages` the public surface, `account` the signed-in member, `host` the
 * back-of-house console.
 */
app.route("/", pages);
app.route("/", account);
app.route("/", host);

/**
 * Serves files from `design/assets/` (see `src/assets.ts`, generated by
 * `npm run assets`). Use `asset("name")` to build the URL rather than typing
 * "/assets/..." by hand.
 */
app.get("/assets/*", async (c) => {
  const path = c.req.path.slice("/assets/".length);
  const object = await c.env.BUCKET?.get(`assets/${path}`);
  if (!object) return c.notFound();
  return new Response(object.body, {
    headers: {
      "content-type": object.httpMetadata?.contentType ?? "application/octet-stream",
      "cache-control": "public, max-age=3600",
      etag: object.httpEtag,
    },
  });
});

app.notFound((c) => {
  createLogger(c.env).debug("route not found", { path: c.req.path });
  return c.json({ error: "Not found" }, 404);
});

app.onError((err, c) => {
  // Logged once, here, where it is handled — not at every level on the way up.
  createLogger(c.env).error("unhandled error", { path: c.req.path, err });
  return c.json({ error: "Internal server error" }, 500);
});

// The default export IS the Worker. Keep it.
export default app;
